---
- name: 'add php APT repository'
  become: true
  ansible.builtin.deb822_repository:
    name: php
    uris: https://ppa.launchpadcontent.net/ondrej/php/ubuntu
    signed_by: https://keyserver.ubuntu.com/pks/lookup?op=get&search=0xb8dc7e53946656efbce4c1dd71daeaab4ad4cab6
    suites: '{{ ansible_distribution_release }}'
    components: main
  notify: update apt cache

- name: 'flush handlers'
  ansible.builtin.meta: flush_handlers

- name: 'install PHP'
  become: true
  ansible.builtin.package:
    state: latest
    name:
      - 'php{{ php_version }}-bcmath' # for precision floats
      - 'php{{ php_version }}-cli' # command-line interpreter
      - 'php{{ php_version }}-curl' # CURL module
      - 'php{{ php_version }}-fpm' # FPM-CGI binary
      - 'php{{ php_version }}-gd' # GD module (images)
      - 'php{{ php_version }}-igbinary'
      - 'php{{ php_version }}-imap' # IMAP module
      - 'php{{ php_version }}-intl' # intl module
      - 'php{{ php_version }}-mbstring' # MBSTRING module (non-ascii strings)
      - 'php{{ php_version }}-memcached'
      - 'php{{ php_version }}-msgpack'
      - 'php{{ php_version }}-mysql'
      - 'php{{ php_version }}-pgsql' # PostgreSQL module
      - 'php{{ php_version }}-redis' # extension for interfacing with Redis
      - 'php{{ php_version }}-soap' # SOAP module
      - 'php{{ php_version }}-sqlite3' # SQLite extension
      - 'php{{ php_version }}-xdebug' # XDebug module
      - 'php{{ php_version }}-xml' # for working with xml data
      - 'php{{ php_version }}-xmlrpc' # XMLRPC-EPI module
      - 'php{{ php_version }}-zip' # required for ZipArchive class
  notify:
    - restart php-fpm

- name: 'lock PHP version'
  become: true
  community.general.alternatives:
    name: php
    path: '/usr/bin/php{{ php_version }}'

# - name: 'start php-fpm service'
#   become: true
#   service:
#     name: 'php{{ php_version }}-fpm'
#     state: started
