---
# Install with `ansible-galaxy install -r requirements.yml`
# Update with `ansible-galaxy install -r requirements.yml --force`
collections:
  - name: community.general

roles:
  - name: geerlingguy.composer
  - name: geerlingguy.docker
  - name: geerlingguy.go
  # - name: geerlingguy.pip
  - name: robertdebock.auditd
