---
- name: 'install supervisor'
  become: true
  ansible.builtin.package:
    state: latest
    name: supervisor

- name: 'start supervisor'
  become: true
  service:
    name: supervisor
    state: started
    enabled: true
